// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH2lvMFtIoHPuKa7hd9QRJKARLVbgNWWA',
    appId: '1:1048672677867:web:32efb796d3db32ea6fb3ae',
    messagingSenderId: '1048672677867',
    projectId: 'booknest-d5565',
    authDomain: 'booknest-d5565.firebaseapp.com',
    storageBucket: 'booknest-d5565.firebasestorage.app',
    measurementId: 'G-QZMHB95FV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdulwPKbwpZTBG2ljW6BgSt6hIWRRzFIU',
    appId: '1:1048672677867:android:61bae34753e919716fb3ae',
    messagingSenderId: '1048672677867',
    projectId: 'booknest-d5565',
    storageBucket: 'booknest-d5565.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAANmZ3LoR-upUjxje1CXGK5luB3dZX-xI',
    appId: '1:1048672677867:ios:3c06e70138e748d26fb3ae',
    messagingSenderId: '1048672677867',
    projectId: 'booknest-d5565',
    storageBucket: 'booknest-d5565.firebasestorage.app',
    iosBundleId: 'com.example.booknest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAANmZ3LoR-upUjxje1CXGK5luB3dZX-xI',
    appId: '1:1048672677867:ios:3c06e70138e748d26fb3ae',
    messagingSenderId: '1048672677867',
    projectId: 'booknest-d5565',
    storageBucket: 'booknest-d5565.firebasestorage.app',
    iosBundleId: 'com.example.booknest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH2lvMFtIoHPuKa7hd9QRJKARLVbgNWWA',
    appId: '1:1048672677867:web:07a903c247369bca6fb3ae',
    messagingSenderId: '1048672677867',
    projectId: 'booknest-d5565',
    authDomain: 'booknest-d5565.firebaseapp.com',
    storageBucket: 'booknest-d5565.firebasestorage.app',
    measurementId: 'G-DY25WSYY9R',
  );
}
